---
- hosts: all
  vars:
    reg_expression:
      - ".*hard.*memlock.*unlimited"
      - ".*soft.*memlock.*unlimited"
      - ".*hard.*nofile.*65536"
    insertvalue:
      - "* hard memlock unlimited"
      - "* soft memlock unlimited"
      - "* hard nofile 65536"
  become: yes
  become_method: sudo
  # vars_files:
  #   - vars/main.yml
  roles:
    - role: ansible-role-java
    - role: ansible-role-common
    # - ansible-role-maven
    - role: geerlingguy.docker
    - role: singleplatform-eng.users
      users:
      - username: vagrant
        # 'wheel', - BSD
        groups: ['sudo', 'docker','adm']
        append: yes
        uid: 1000
        home: /home/vagrant
    - role: bossjones.bootstrap
    - role: bossjones.python
    # - role: bossjones.ansible-vagrant-setup
    # - role: bossjones.perf-tools
    - role: debops.apt
    - role: debops.bootstrap
    - role: debops.core
    - role: debops.debug
    # - role: debops.swapfile
    #   swapfile_size: '{{ 2 * ansible_memtotal_mb }}'

    # - role: bossjones-ipv6
    # - role: ksylvan.docker
    # - role: motd
    # - role: bossjones-firewalld
    # - role: mjanser.powerline
    # - role: joshualund.golang
    # - role: common
    #   theme: "powerline-plain"
    #   repository: https://github.com/revans/bash-it.git
    #   version: master
    #   aliases:
    #     - general
    #   plugins:
    #     - base
    #     - history
    #   completions:
    #     - git
    # - role: bossjones-cli-tools

  pre_tasks:

    - name: Fail if Ansible is ancient
      fail: msg="We need Ansible >= 2.0. Please update your kit. 'pip install -U Ansible'"
      when: ansible_version.major < 2
      tags:
        - always

    - name: Include vars from local-configure.yml if found
      include_vars: "{{ item }}"
      with_first_found:
       - null.yml

    - name: Install jq
      apt: name=jq state=latest install_recommends=yes
      become: yes

    - lineinfile:
        path: /etc/security/limits.conf
        regexp: "{{item.0}}"
        line: "{{item.1}}"
        state: present
        insertbefore: "^\\#\\*"
      with_together:
        - "{{reg_expression}}"
        - "{{insertvalue}}"
      become: yes

    - lineinfile:
        path: /etc/sysctl.conf
        regexp: "^vm.max_map_count = 262144"
        line: vm.max_map_count = 262144
        state: present
        insertbefore: EOF
      become: yes
