---
- name: Set ulimit for vagrant user.
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
  tags: installation

- name: Set system limit.
  sysctl:
    name: fs.file-max
    value: "{{ global_file_max_limit }}"
    state: present
  tags: installation

- name: Activate PAM limits module for su.
  lineinfile:
    dest: /etc/pam.d/su
    state: present
    regexp: "^#?.*session    required   pam_limits.so"
    line: "session    required   pam_limits.so"
  tags: installation


- name: Apply sysctl options
  sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
  with_items:
      - { name: "net.ipv4.conf.all.send_redirects", value: "0"}
      - { name: "net.ipv4.conf.default.send_redirects", value: "0"}
      - { name: "net.ipv4.conf.all.accept_source_route", value: "0"}
      - { name: "net.ipv4.conf.default.accept_source_route", value: "0"}
      - { name: "net.ipv4.conf.all.accept_redirects", value: "0"}
      - { name: "net.ipv4.conf.default.accept_redirects", value: "0"}
      - { name: "net.ipv4.conf.all.log_martians", value: "0"}
      - { name: "net.ipv4.conf.default.log_martians", value: "0"}
      - { name: "net.ipv4.icmp_echo_ignore_broadcasts", value: "1"}
      - { name: "net.ipv4.icmp_ignore_bogus_error_responses", value: "1"}
      - { name: "net.ipv4.tcp_syncookies", value: "1"}
      - { name: "net.ipv6.conf.all.accept_ra", value: "0"}
      - { name: "net.ipv6.conf.default.accept_ra", value: "0"}
      - { name: "net.ipv6.conf.all.accept_redirects", value: "0"}
      - { name: "net.ipv6.conf.default.accept_redirects", value: "0"}
